### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by AndShum** [CCallahanIV/FiveStar#5]
***mobile first design
-Design header (site title, nav, etc.)
-Build out teaser bar's functionality. I.E. placement of picture, name, rating etc.
-hide/show the details page from the teaser
-what do we want to have showing before data loads??
-build out <iframe> functionality for the maps.  (one general map or load a separate map for each shop).
-filter returned list to top 5 or nearest 5 options.
-button to show next 5 options in list??
-add a footer.

***STRETCH
-add a delete button to remove any options we do not want
-when item is deleted, new item populates in its place
-add options for different types of shops.

**Comment by CCallahanIV** [comment]
LEFTOVERS:

 STRETCH:
- Different shops (not restaurants)
- Store favorites
- Remember trash icon
